version: '3'
services:
  books-service:
    build:
      context: ./books-service
    ports:
      - '3000:3000'
  authors-service:
    build:
      context: ./authors-service
    ports:
      - '4000:4000'
  categories-service:
    build:
      context: ./categories-service
    ports:
      - '5000:5000'
